### PR TITLE
Support laterpay-client v3 and v4

### PR DESCRIPTION
**Pull request by suligap**

### CODE REVIEW

**Comment by doismellburning** [comment]
Fair point! I'm thinking the `.travis.yml` is getting unwieldy though.

What do you think about abandoning the Travis parallelisation?

**Comment by suligap** [comment]
Absolutely :+1:

**Comment by slafs** [comment]
LGTM.

Funny. Simple `tox` (with every env) ran for around 5-6 min. and a parallel/matrix build ran for over 12 min.?

One thing we're missing now tough is the `allow_failures` feature, which may bit us later.

**Comment by doismellburning** [comment]
> One thing we're missing now tough is the allow_failures feature, which may bit us later.

@slafs Absolutely

What do you and @suligap think about dropping the `djangodev` tests?

**Comment by suligap** [comment]
Seems reasonable :+1:

**Comment by doismellburning** [comment]
Awesome cheers!

**Pull request merged**
